version: '3'

services:

    # nginx
    nginx-service:
        image: nginx:stable-alpine
        container_name: nginx
        restart: always # always restart unless stopped manually
        ports:
            - "8080:80"
        volumes:
            - ./api:/var/www/api
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
            - mysql
        networks:
            - internal

    # php
    php:
        build:
            context: .
            dockerfile: ./php/Dockerfile
        container_name: php
        restart: always # always restart unless stopped manually
        ports:
            - "9000:9000"
        volumes:
            - ./api:/var/www/api
        networks:
            - internal

    # mysql
    mysql:
        image: mysql
        container_name: mysql
        ports:
            - 4306:3306
        volumes:
            - db-data:/var/lib/mysql
        restart: always # always restart unless stopped manually
        environment:
            MYSQL_ROOT_PASSWORD: wikifoot
            MYSQL_USER: wikifoot
            MYSQL_PASSWORD: wikifoot
            MYSQL_DATABASE: wikifoot
        networks:
            - internal

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        networks:
            - internal
        depends_on:
            - mysql
        links:
            - mysql
        environment:
            PMA_HOST: mysql
        restart: always
        ports:
            - 8081:80

networks:
    internal:
volumes:
    db-data: {}